# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_auto_20160517_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='rating',
            field=models.IntegerField(choices=[(1, 'G'), (2, 'PG'), (3, 'PG-13'), (4, '14A'), (5, 'R'), (6, 'NR')], default=1),
        ),
    ]
