# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 23:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_suggestion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.datetime(2016, 6, 14, 23, 17, 9, 411384, tzinfo=utc)),
        ),
    ]
