# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 21:07
from __future__ import unicode_literals

from django.db import migrations, models

def load_libapp_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "libapp")

class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_auto_20160614_1917'),
    ]

    operations = [
        migrations.RunPython(load_libapp_from_fixture),
    ]
