# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 04:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import libapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0008_auto_20160623_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='libuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=libapp.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 24)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
