# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0009_auto_20160624_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 26)),
        ),
        migrations.AlterField(
            model_name='libuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='photos/user.png', null=True, upload_to='photos/'),
        ),
    ]
